import = [
	"~/.config/alacritty/bl1nk.toml",
	"~/.config/alacritty/keybinds.toml"
]
live_config_reload = true
ipc_socket = true
[shell]
	program = "/bin/zsh"
[window]
	#decorations = "None"
	opacity = 0.9
	blur = true
	#dynamic_title = false
	class = { instance = "Alacritty", general = "Alacritty" }
[scrolling]
	history = 30000
	multiplier = 1
[bell]
	duration = 0
[cursor.style]	
	shape = "Block"
	blinking = "Never"
[terminal]
	osc52 = "CopyPaste"
[mouse]
	hide_when_typing = true
[[hints.enabled]]
	command = "xdg-open"
	regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
	hyperlinks = true
	post_processing = true
	persist = true
	mouse = { mods = "Control|Shift", enabled = true } 