[font]
	size = 12
	builtin_box_drawing = true
[font.normal]
	family = "Hack"
[colors]
	transparent_background_colors = true
	draw_bold_text_with_bright_colors = true
[colors.primary]
	foreground = "#A0A0A0"
	bright_foreground = "#FFFFFF"
	dim_foreground = "#A0A0A0"
	background = "#111111"
[colors.normal]
	black = "#1A1C1D"
	red = "#F92571"
	green = "#81B313"
	yellow = "#FD961E"
	blue = "#4E81AA"
	magenta = "#8B54FE"
	cyan = "#465456"
	white = "#CBCBC5"
[colors.bright]
	black = "#505354"
	red = "#FF5894"
	green = "#B5E354"
	yellow = "#FEED6B"
	blue = "#0B72C1"
	magenta = "#9D6EFE"
	cyan = "#889BA1"
	white = "#F8F8F2"
[colors.dim]
	black = "#1A1C1D"
	red = "#F92571"
	green = "#81B313"
	yellow = "#FD961E"
	blue = "#4E81AA"
	magenta = "#8B54FE"
	cyan = "#465456"
	white = "#CBCBC5"
