[keyboard]
	bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "0", mods = "Control", action = "ResetFontSize" },
	{ key = "-", mods = "Control", action = "DecreaseFontSize" },
	{ key = "=", mods = "Control", action = "IncreaseFontSize" },
]
