################################################################
#
#	                 _
#	 _   _  __ _ ___(_)
#	| | | |/ _` |_  / |
#	| |_| | (_| |/ /| |
#	 \__, |\__,_/___|_|
#	 |___/
#
# https://yazi-rs.github.io/
################################################################
[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
title_format   = "Yazi: {cwd}"


[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_quality   = 90
sixel_fraction  = 10
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]


[opener]
editor = [
	{ run = '${EDITOR:-vim} "${@}"', desc = "Edit files in $EDITOR", block = true, for = "linux" },
]
extractor = [
	{ run = 'vim "${@}"', desc = "Open archives in vim", block = true, for = "linux" },
]
viewer = [ 
	{ run = 'kitten icat "${@}" && read', desc = "Display images in icat", block = true, for = "linux" },
]
player = [
	{ run = 'mpv --force-window "${@}"', desc = "Play audios or videos in mpv", orphan = true, for = "linux" },
]
match = [
	{ run = 'xdg-open "${@}"', desc = "Open files in the user's preferred application", orphan = true, for = "linux" },
]


[open]
rules = [
	{ name = "*.{md}", use = [ "match" ] },
	{ name = "*.{lua}", use = [ "editor", "match" ] },
	{ mime = "application/{json,x-ndjson}", use = [ "editor", "match" ] },
	{ mime = "text/*", use = [ "editor", "match" ] },
	{ mime = "image/*", use = [ "viewer","match" ] },
	{ mime = "{audio,video}/*", use = [ "player", "match" ] },
	{ mime = "application/{,g}zip", use = [ "extractor", "match" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extractor", "match" ] },
	{ name = "*", use = [ "match" ] },
]


[log]
enable = false
