general-options:
  healthProviders:
    &healthProviders {
      url: https://www.gstatic.com/generate_204,
      lazy: true,
      interval: 600,
      timeout: 3000,
    }
  healthProxies:
    &healthProxies {
      url: https://www.gstatic.com/generate_204,
      lazy: true,
      interval: 300,
      timeout: 5000,
    }

providers-options:
  proxyProvidersCommon:
    &proxyProvidersCommon {
      type: http,
      health-check: { enable: true, <<: *healthProviders },
    }
  proxyProvidersProxy: &proxyProvidersProxy { proxy: 🇯🇵 JP }
  ruleProvidersCommon:
    &ruleProvidersCommon {
      type: http,
      behavior: classical,
      format: yaml,
      interval: 86400,
    }

proxy-groups-options:
  proxyGroupsCommon:
    &proxyGroupsCommon { <<: *healthProxies, max-failed-times: 3 }
  proxyGroupsInclude:
    &proxyGroupsInclude { <<: *proxyGroupsCommon, include-all: true }
  proxyGroupsUse:
    &proxyGroupsUse {
      use: [example1, example2, example3],
      <<: *proxyGroupsCommon,
    }
  proxyGroupsFiltered:
    &proxyGroupsFiltered {
      proxies:
        [
          🇦🇷 AR,
          🇭🇰 HK,
          🇯🇵 JP,
          🇳🇬 NG,
          🇷🇺 RU,
          🇸🇬 SG,
          🇹🇼 TW,
          🇹🇷 TR,
          🇬🇧 UK,
          🇺🇸 US,
          🌏 C1,
          🌏 C2,
          🌏 C3,
        ],
    }
  proxyGroupsSelected: &proxyGroupsSelected { proxies: [🇸🇬 SG, 🇺🇸 US] }
  proxyGroupsCombined:
    &proxyGroupsCombined {
      proxies:
        [
          🌐 DIRECT,
          🚫 REJECT,
          🧅 TOR,
          🫴 MANUAL,
          🚘 AUTO,
          🔙 FALL,
          ⏭️ SEL,
          🇦🇷 AR,
          🇭🇰 HK,
          🇯🇵 JP,
          🇳🇬 NG,
          🇷🇺 RU,
          🇸🇬 SG,
          🇹🇼 TW,
          🇹🇷 TR,
          🇬🇧 UK,
          🇺🇸 US,
          🌏 C1,
          🌏 C2,
          🌏 C3,
        ],
    }

bind-address: "*"
mixed-port: 37897
external-controller: 127.0.0.1:9000
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
log-level: info
allow-lan: false
ipv6: false
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 300
global-ua: clash.meta
profile:
  store-selected: true
  store-fake-ip: false

geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb

dns:
  enable: true
  prefer-h3: true
  ipv6: false
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 100.64.0.1/10
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - geosite:private
    - geosite:cn
  default-nameserver:
    - 223.5.5.5
    - 9.9.9.9
  nameserver-policy:
    geosite:private: system
    geosite:cn:
      - https://dns.alidns.com/dns-query#skip-cert-verify=true
      - https://doh.pub/dns-query#skip-cert-verify=true
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#skip-cert-verify=true
    - https://doh.pub/dns-query#skip-cert-verify=true
  direct-nameserver:
    - system
  nameserver:
    - https://dns.alidns.com/dns-query#skip-cert-verify=true
    - https://doh.pub/dns-query#skip-cert-verify=true
  fallback:
    - 9.9.9.9
    - 101.101.101.101
  fallback-filter:
    geoip: true
    geoip-code: CN

hosts:
  "localhost": 127.0.0.1

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
  skip-domain:
    - +.lan
    - +.local
    - +.localhost

tun:
  enable: true
  stack: mixed
  device: meta0
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: true
  route-exclude-address:
    - 1.1.1.1/32
    - 209.250.254.15/32
    - 8.153.99.116/32
  dns-hijack:
    - any:53
  mtu: 1500

proxy-providers:
  example1:
    <<:
      - *proxyProvidersCommon
    interval: 3600
    url: https://raw.githubusercontent.com/example1/example1.yaml
    path: ./proxy_providers/example1.yaml
    header:
      Accept:
        - "application/vnd.github.raw+json"
      Authorization:
        - "Bearer token"
  example2:
    <<:
      - *proxyProvidersCommon
    url: https://example2.org
    path: ./proxy_providers/example2.yaml
  example3:
    <<:
      - *proxyProvidersCommon
      - *proxyProvidersProxy
    interval: 3600
    url: https://example3.org
    path: ./proxy_providers/example3.yaml

proxies:
  [
    {
      name: 🧅 TOR,
      type: socks5,
      server: 127.0.0.1,
      port: 9050,
      udp: true,
      ip-version: ipv4,
    },
  ]

proxy-groups:
  - { name: 🌐 DIRECT, type: select, proxies: [DIRECT] }
  - { name: 🚫 REJECT, type: select, proxies: [REJECT] }
  - {
      name: 🫴 MANUAL,
      type: select,
      proxies:
        [
          🌐 DIRECT,
          🚫 REJECT,
          🧅 TOR,
          🚘 AUTO,
          🔙 FALL,
          ⏭️ SEL,
          🇦🇷 AR,
          🇭🇰 HK,
          🇯🇵 JP,
          🇳🇬 NG,
          🇷🇺 RU,
          🇸🇬 SG,
          🇹🇼 TW,
          🇹🇷 TR,
          🇬🇧 UK,
          🇺🇸 US,
          🌏 C1,
          🌏 C2,
          🌏 C3,
        ],
    }
  - {
      name: 🚘 AUTO,
      type: url-test,
      tolerance: 30,
      max-failed-times: 3,
      <<: [*proxyGroupsFiltered, *healthProxies],
    }
  - {
      name: 🔙 FALL,
      type: fallback,
      max-failed-times: 3,
      <<: [*proxyGroupsFiltered, *healthProxies],
    }
  - {
      name: ⏭️ SEL,
      type: fallback,
      max-failed-times: 3,
      <<: [*proxyGroupsSelected, *healthProxies],
    }

  - {
      name: 🇦🇷 AR,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇦🇷|阿根廷|argentina",
    }
  - {
      name: 🇭🇰 HK,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇭🇰|香港|hongkong",
    }
  - {
      name: 🇯🇵 JP,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇯🇵|日本|japan",
    }
  - {
      name: 🇳🇬 NG,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇳🇬|尼日利亚|nigeria",
    }
  - {
      name: 🇷🇺 RU,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇷🇺|俄罗斯|俄羅斯|russia",
    }
  - {
      name: 🇸🇬 SG,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇸🇬|新加坡|狮城|獅城|singapore",
    }
  - {
      name: 🇹🇼 TW,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇹🇼|台湾|臺灣|taiwan",
    }
  - {
      name: 🇹🇷 TR,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇹🇷|土耳其|turkey",
    }
  - {
      name: 🇬🇧 UK,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇬🇧|英|英國|伦敦|england|kingdom|britsh",
    }
  - {
      name: 🇺🇸 US,
      <<: *proxyGroupsInclude,
      type: select,
      filter: "(?i)🇺🇸|美国|美國|西雅图|西雅圖|洛杉矶|洛杉磯|艾斯本|america|states|seattle|angeles|ashburn",
    }
  - { name: 🌏 C1, <<: *proxyGroupsInclude, type: select, exclude-filter: "🧅" }
  - { name: 🌏 C2, <<: *proxyGroupsInclude, type: select, exclude-filter: "🧅" }
  - { name: 🌏 C3, <<: *proxyGroupsInclude, type: select, exclude-filter: "🧅" }

  - { name: 🔊 ADS, type: select, proxies: [🌐 DIRECT, 🚫 REJECT, 🫴 MANUAL] }
  - { name: 🤖 AI, type: select, <<: *proxyGroupsCombined }
  - { name: 🍎 Apple, type: select, <<: *proxyGroupsCombined }
  - { name: 🦉 Google, type: select, <<: *proxyGroupsCombined }
  - { name: 🧪 YouTube, type: select, <<: *proxyGroupsCombined }
  - { name: 🥅 Netflix, type: select, <<: *proxyGroupsCombined }
  - { name: 🐭 Disney, type: select, <<: *proxyGroupsCombined }
  - { name: 👌 HBO, type: select, <<: *proxyGroupsCombined }
  - { name: 🧙🏿‍♀️ Twitch, type: select, <<: *proxyGroupsCombined }
  - { name: 🐦 Twitter, type: select, <<: *proxyGroupsCombined }
  - { name: 📲 Telegram, type: select, <<: *proxyGroupsCombined }
  - { name: 🚂 Steam, type: select, <<: *proxyGroupsCombined }
  - { name: 🪟 Microsoft, type: select, <<: *proxyGroupsCombined }
  - { name: 📈 IPinfo, type: select, <<: *proxyGroupsCombined }
  - { name: 👂 Spotify, type: select, <<: *proxyGroupsCombined }
  - { name: 🪙 Crypto, type: select, <<: *proxyGroupsCombined }
  - { name: 🀄 Manchuria, type: select, <<: *proxyGroupsCombined }
  - { name: 🪜 Proxy, type: select, <<: *proxyGroupsCombined }
  - { name: 🐟 Leakage, type: select, <<: *proxyGroupsCombined }

rule-providers:
  ads:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml
    path: ./ruleset/ads.yaml
  ipinfo:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.yaml
    path: ./ruleset/ipinfo.yaml
  google:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: ./ruleset/google.yaml
  youtube:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/youtube.yaml
  netflix:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml
    path: ./ruleset/netflix.yaml
  disney:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml
    path: ./ruleset/disney.yaml
  hbo:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/HBO/HBO.yaml
    path: ./ruleset/hbo.yaml
  openai:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
  anthropic:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Anthropic/Anthropic.yaml
    path: ./ruleset/anthropic.yaml
  gemini:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.yaml
    path: ./ruleset/gemini.yaml
  twitch:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitch/Twitch.yaml
    path: ./ruleset/twitch.yaml
  twitter:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml
    path: ./ruleset/twitter.yaml
  telegram:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/telegram.yaml
  spotify:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/spotify.yaml
  microsoft:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/microsoft.yaml
  apple:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml
    path: ./ruleset/apple.yaml
  steam:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/steam.yaml
  binance:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Binance/Binance.yaml
    path: ./ruleset/binance.yaml
  okx:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/OKX/OKX.yaml
    path: ./ruleset/okx.yaml
  wechat:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/WeChat/WeChat.yaml
    path: ./ruleset/wechat.yaml
  xhs:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/XiaoHongShu/XiaoHongShu.yaml
    path: ./ruleset/xhs.yaml
  douban:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/DouBan/DouBan.yaml
    path: ./ruleset/douban.yaml
  cn:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml
    path: ./ruleset/cn.yaml
  proxy:
    <<: *ruleProvidersCommon
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy.yaml
    path: ./ruleset/proxy.yaml

rules:
  - RULE-SET,ads,🔊 ADS
  - GEOSITE,category-ads-all,🔊 ADS
  - RULE-SET,ipinfo,📈 IPinfo
  - DOMAIN,check.torproject.org,📈 IPinfo
  - DOMAIN-SUFFIX,ip.sb,📈 IPinfo
  - DOMAIN-SUFFIX,myip.la,📈 IPinfo
  - DOMAIN-SUFFIX,ipip.net,📈 IPinfo
  - DOMAIN-SUFFIX,ipinfo.io,📈 IPinfo
  - RULE-SET,youtube,🧪 YouTube
  - RULE-SET,netflix,🥅 Netflix
  - RULE-SET,disney,🐭 Disney
  - RULE-SET,hbo,👌 HBO
  - RULE-SET,openai,🤖 AI
  - RULE-SET,anthropic,🤖 AI
  - RULE-SET,gemini,🤖 AI
  - RULE-SET,twitch,🧙🏿‍♀️ Twitch
  - RULE-SET,twitter,🐦 Twitter
  - RULE-SET,telegram,📲 Telegram
  - RULE-SET,google,🦉 Google
  - RULE-SET,spotify,👂 Spotify
  - RULE-SET,microsoft,🪟 Microsoft
  - RULE-SET,apple,🍎 Apple
  - RULE-SET,steam,🚂 Steam
  - GEOSITE,bybit,🪙 Crypto
  - RULE-SET,binance,🪙 Crypto
  - RULE-SET,okx,🪙 Crypto
  - GEOSITE,redotpay,🪙 Crypto
  - RULE-SET,wechat,🀄 Manchuria
  - RULE-SET,xhs,🀄 Manchuria
  - RULE-SET,douban,🀄 Manchuria
  - GEOSITE,private,🌐 DIRECT
  - RULE-SET,cn,🌐 DIRECT
  - DOMAIN-SUFFIX,cn,🌐 DIRECT
  - DOMAIN-KEYWORD,-cn,🌐 DIRECT
  - DOMAIN-KEYWORD,rustdesk,🌐 DIRECT
  - DOMAIN-KEYWORD,dell,🌐 DIRECT
  - DOMAIN-SUFFIX,right.com.cn,🌐 DIRECT

  - IP-CIDR,9.9.9.9/32,🌐 DIRECT,no-resolve
  - IP-CIDR,101.101.101.101/32,🌐 DIRECT,no-resolve
  - GEOIP,PRIVATE,🌐 DIRECT,no-resolve
  - GEOIP,CN,🌐 DIRECT,no-resolve

  - PROCESS-PATH-REGEX,.*rustdesk,🌐 DIRECT
  - AND,((DOMAIN,hf.co),(DST-PORT,22)),🌐 DIRECT

  - RULE-SET,proxy,🪜 Proxy
  - GEOSITE,geolocation-!cn,🪜 Proxy
  - MATCH,🐟 Leakage
